# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'Mostly about AppSec and .NET'
description:      
url:              https://blog.fennec.dev
baseurl:          "/"

author:
  name:           'Niels Tanis'
  url:            https://twitter.com/nielstanis

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
